# -*- coding: utf-8 -*-
"""WhatsApp Android Exporter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUdDkogDRLE4CbOMCWsGqN_oVHQOA3FN

#WhatsApp Android Exporter
Decrypts WhatsApp .crypt15 files, given the 64-character long key.

The output result is either a SQLite database or a ZIP file (in case of wallpapers and stickers).

### Step 1: Download the files from your device

1. Enable a WhatsApp E2E encrypted backup
2. [Enable USB debugging](https://developer.android.com/studio/debug/dev-options)
3. [Install adb](https://developer.android.com/tools/releases/platform-tools)
4. Pull the files with:
  ```bash
  adb pull /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Databases ./
  adb pull /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Backups ./
  ```
"""

#@title Step 2: Upload your .crypt15 files

from google.colab import files
uploaded = files.upload()

#@title Step 3: Run decryption
encryptionKey = "" #@param {type:"string"}

# Install wa-crypt-tools
!python -m pip install git+https://github.com/ElDavoo/wa-crypt-tools

import re
trimmedEncryptionKey = re.sub(r'[^0-9a-fA-F]', '', encryptionKey)
if not trimmedEncryptionKey:
  raise Exception("Missing encryptionKey")

# Convert the hexadecimal key to a key file
!wacreatekey --hex "{encryptionKey}"

# Find and decrypt all .crypt15 files
import glob
import os
crypt15_files = glob.glob('*.crypt15')
if not crypt15_files:
  raise Exception("No .crypt15 files found in the current directory.")
else:
  for encrypted_file in crypt15_files:
    decrypted_file = os.path.splitext(encrypted_file)[0]  # Remove the .crypt15 extension
    print(f"Decrypting {encrypted_file} to {decrypted_file}")
    !wadecrypt encrypted_backup.key {encrypted_file} {decrypted_file}
    print(f"Finished decrypting {encrypted_file}")

"""### Step 4: View your files

You can view the .db file with a [SQLite Viewer](https://inloop.github.io/sqlite-viewer/)
"""

